### ISSUE TITLE
Cannot Start 6.0.2 on Win64 with Mathematica 10

### ISSUE THREAD

**Issue by ghost** [NetLogo/Mathematica-Link#3]
The old version (5.3.1) worked, but I tried to upgrade myself to 6.0.2.
So Install-ed again the package at File (in Mathematica), then:
<<NetLogo'
NLStart[] - it wanted me to relocate the folder so I chose: C://Program Files//NetLogo 6.0.2
And every time I got the following error:

> FileExistsQ::fstr: File specification Missing[NotFound] is not a string of one or more characters. >>
> Java::excptn: A Java exception occurred: java.lang.ClassNotFoundException: NLink
> 	at java.net.URLClassLoader$1.run(Unknown Source)
> 	at java.net.URLClassLoader$1.run(Unknown Source)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.net.URLClassLoader.findClass(Unknown Source)
> 	at java.lang.ClassLoader.loadClass(Unknown Source)
> 	at java.lang.ClassLoader.loadClass(Unknown Source)
> 	at java.lang.Class.forName0(Native Method)
> 	at java.lang.Class.forName(Unknown Source). 
> LoadJavaClass::fail: Java failed to load class NLink. >>

What shall I do?

**Comment by ghost** [comment]
Solved with installing Mathematica 11, I couldn't set the Java of Mathematica 10 to 1.8.x...
