### ISSUE TITLE
Error running Mathematica-Link

### ISSUE THREAD

**Issue by evolvingtech** [NetLogo/Mathematica-Link#5]
Trying to run Mathematica Link for NetLogo (Ver. 6.2.1 for Windows) - error occurs after running NLStart[] and pointing it to the NetLogo application directory.

`"A Java exception occurred: "java.lang.UnsupportedClassVersionError: NLink : Unsupported major.minor version 52.0"
`

At the operating system level, JDK is installed.

```
java -version
java version "17.0.1" 2021-10-19 LTS
Java(TM) SE Runtime Environment (build 17.0.1+12-LTS-39)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.1+12-LTS-39, mixed mode, sharing)

```
One more note... the version of Mathematica is 10.1, which I understand is supposed to work with Mathematica-Link/NetLogo.

**Comment by LaCuneta** [comment]
Thanks for reporting this issue, and sorry you ran into it.  Mathematica 10.1 should still be supported, but I haven't been able to test it in a while. 

That error message makes it sound to me like Mathematica is using Java 7 to try to run Mathematica-Link and NetLogo.  Can you run `NLJavaDiagnostics[]` from Mathematica and report what it outputs?  That should give the Java version it's actually trying to use.

**Comment by evolvingtech** [comment]
```
NLJavaDiagnostics[]
<|"javaVersion" -> "1.7.0_13", "javaArchitecture" -> "64"|> 
```

**Comment by LaCuneta** [comment]
Yeah, that's Java 7 alright.  So we can try to get it using Java 17.  The `NLStart[]` command takes in the options to pass to to [JLink's `InstallJava[]` command](https://reference.wolfram.com/language/JLink/tutorial/CallingJavaFromTheWolframLanguage.html#21634).  My Mathematica syntax is rusty, but we should be able to pass the arg like this:

```
NLStart["", CommandLine -> "/your/path/to/java17/java"]
```

That `CommandLine` option is the one that'll get sent along to `InstallJava[]`, you'll just need the full path to its `java` executable file.  You can give it a try with Java 17 and it might work just fine, but for NetLogo we only officially support Java 8 so that'd be worth a try if it doesn't.  

I hope that helps.

**Comment by evolvingtech** [comment]
Unfortunately, this did not work.

```
<< NetLogo`

NLStart["C:\\Program Files\\NetLogo 6.2.1", 
 CommandLine -> "C:\\Program Files\\Java\\jdk-17.0.1\\bin"]
```

and the following is returned:

```
InstallJava::reinst: Java is already running. If you need to specify non-standard options to control how Java is launched, use ReinstallJava instead. >>

Java::excptn: A Java exception occurred: java.lang.UnsupportedClassVersionError: NLink : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$100(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source).

LoadJavaClass::fail: Java failed to load class NLink. >>

OptionValue::nodef: Unknown option CommandLine for NLStart. >>
```

The following info might help to troubleshoot:

```
NLDiagnostics["C:\\Program Files\\NetLogo 6.2.1"]

<|"providedPath" -> "C:\\Program Files\\NetLogo 6.2.1", 
 "jarLookupPaths" -> {"C:\\Program Files\\NetLogo \
6.2.1\\app\\netlogo-6.2.1.jar", 
   "C:\\Program Files\\NetLogo 6.2.1\\Mathematica \
Link\\mathematica-link.jar"}, 
 "foundJars" -> {"C:\\Program Files\\NetLogo \
6.2.1\\app\\netlogo-6.2.1.jar", 
   "C:\\Program Files\\NetLogo 6.2.1\\Mathematica \
Link\\mathematica-link.jar"}, "missingJars" -> {}|>
```

**Comment by LaCuneta** [comment]
Thanks for including the detailed logs, that's very helpful.  Two things pop out at me:

1. I think that path would need to be to the actual Java executable file, so on Windows `CommandLine -> "C:\\Program Files\\Java\\jdk-17.0.1\\bin\\java.exe"`
2. Did you start with a newly launched Mathematica instance?  It might be best to shutdown and re-open to try again fresh so no "old" code is already running.

**Comment by evolvingtech** [comment]
Yes of course, I relaunched Mathematica. Still having the same kind of result. Also note that `CommandLine -> ...` does not appear to be a valid option for `NLStart.`

Here is the output:

```
<< NetLogo`

NLStart["C:\\Program Files\\NetLogo 6.2.1", 
 CommandLine -> "C:\\Program Files\\Java\\jdk-17.0.1\\bin\\java.exe"]

InstallJava::reinst: Java is already running. If you need to specify non-standard options to control how Java is launched, use ReinstallJava instead. >>

Java::excptn: A Java exception occurred: java.lang.UnsupportedClassVersionError: NLink : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$100(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source).

LoadJavaClass::fail: Java failed to load class NLink. >>

OptionValue::nodef: Unknown option CommandLine for NLStart. >>
```

**Comment by LaCuneta** [comment]
Again, my apologies as I don't have a copy of Mathematica to test on at the moment.

The `NLStart` command [should take in an `opts` argument](https://github.com/NetLogo/Mathematica-Link/blob/master/NetLogo.m#L234) that will then be [passed to the `InstallJava` command for JLink](https://github.com/NetLogo/Mathematica-Link/blob/master/NetLogo.m#L264).  That `opts` argument should include the `CommandLine` setting, per the docs I linked earlier.

Maybe it should be something like this, with the curly braces for the `opts`?  `NLStart["C:\\Program Files\\NetLogo 6.2.1", 
 {CommandLine -> "C:\\Program Files\\Java\\jdk-17.0.1\\bin\\java.exe"}]`

**Comment by evolvingtech** [comment]
Still not working. I have a feeling this will have to wait till you have a copy of Mathematica to test.

**Comment by LaCuneta** [comment]
After more digging, I did some re-work to the package to make sure the `CommandLine` setting gets passed correctly through to JLink.  I posted a [new version of the package here](https://github.com/NetLogo/Mathematica-Link/releases/tag/6.1.2).  You can safely unzip that over the existing `Mathematica-Link` folder in your NetLogo folder, backing up what's there already if you want to.  You will have to [uninstall the existing NetLogo package from Mathematica](https://community.wolfram.com/groups/-/m/t/1176419) before re-installing this new one.

After installing, this syntax should work (paths replaced for your Windows sytem, of course): 

```mathematica
NLStart["/Applications/NetLogo 6.2.1", CommandLine -> "/Library/Java/JavaVirtualMachines/liberica-jdk-17-full.jdk/Contents/Home/bin/java"];
```

Let me know if that helps or if you have any issues with it.

**Comment by evolvingtech** [comment]
Thank you for this update. The issue still remains, but I think it's getting close to resolution. Here are the steps I performed.

Downloaded the [new version of the package](https://github.com/NetLogo/Mathematica-Link/releases/tag/6.1.2) and unzipped it. 

Placed the contents of the unzipped file into the Mathematica Link folder where the NetLogo 6.2.1 application is installed.

Uninstalled the NetLogo package from Mathematica. (For others unsure how to do this, launch Mathematica, and in an open Mathematica Notebook evaluate `$BaseDirectory`. Inside this directory there should be an Applications folder which will contain a `NetLogo.m` file. Quit the Mathematica application. Deleted the NetLogo.m file from this directory.)

Launched Mathematica and installed the NetLogo package (in the Mathematica menu `File --> Install --> Package source From file --> NetLogo.m` which is the updated file just downloaded and unzipped.

Loaded the NetLogo package:

`<<NetLogo`
`
The Mathematica notebook recognizes all the "NL" functions defined by `NetLogo.m`.

Tried to start MathematicaLink:
```
NLStart["C:\\Program Files\\NetLogo 6.2.1", 
 CommandLine -> "C:\\Program Files\\Java\\jdk-17.0.1\\bin\\java.exe"]

LinkConnect::linkc: Unable to connect to LinkObject[C:\Program Files\Java\jdk-17.0.1\bin\java.exe -classpath "C:\Program Files\Wolfram Research\Mathematica\10.1\SystemFiles\Links\JLink\JLink.j\[Ellipsis] .JLinkSystemClassLoader com.wolfram.jlink.Install -init "C:\Users\USER_NAME\AppData\Local\Temp\m-8b0af7ec-69df-441e-9b78-2395f6f8d25f",264,5]. >>

InstallJava::fail: A link to the Java runtime could not be established. >>

LoadJavaClass::fail: Java failed to load class NLink. >>
```

If instead I try pointing this to the `bin `directory, it pops open a window to prompt me to `Choose a MathLink program to launch`. It seems to want a `.exe` file. When I select the appropriate java.exe file from the JDK I get the same error response as before.

```
NLStart["C:\\Program Files\\NetLogo 6.2.1", 
 CommandLine -> "C:\\Program Files\\Java\\jdk-17.0.1\\bin"]

LinkObject::linkn: Argument LinkObject["C:\Program Files\Java\jdk-14.0.1\bin\java.exe",311,5] in LinkReadyQ[LinkObject["C:\Program Files\Java\jdk-14.0.1\bin\java.exe",311,5]] has an invalid LinkObject number; the link may be closed. >>

LinkObject::linkn: Argument LinkObject["C:\Program Files\Java\jdk-14.0.1\bin\java.exe",311,5] in LinkConnectedQ[LinkObject["C:\Program Files\Java\jdk-14.0.1\bin\java.exe",311,5]] has an invalid LinkObject number; the link may be closed. >>

LinkObject::linkn: Argument LinkObject["C:\Program Files\Java\jdk-14.0.1\bin\java.exe",311,5] in LinkReadyQ[LinkObject["C:\Program Files\Java\jdk-14.0.1\bin\java.exe",311,5]] has an invalid LinkObject number; the link may be closed. >>

General::stop: Further output of LinkObject::linkn will be suppressed during this calculation. >>

InstallJava::fail: A link to the Java runtime could not be established. >>

LoadJavaClass::fail: Java failed to load class NLink. >>
```

**Comment by LaCuneta** [comment]
Unfortunately I don't have Mathematica 10 to test with, so I can only confirm things worked with Mathematica 12 on macOS with Java 17.   

It's odd to me that it starts with the `C:\Program Files\Java\jdk-17.0.1\bin` path for `CommandLine` but then it actually runs with `jdk-14.0.1`.  I guess that was just you choosing a different JDK from the prompt that popped up?  What happens if you pick Java 17?

The only other thing I can think to try would be to install Java 8 and see if that works any better.

**Comment by evolvingtech** [comment]
You are correct in that I last pointed this to the jdk 14.0.1 java.exe. There were several jdk installations on the OS. I tried them all.

It seems that the Mathematica 10.1 is hardwired to Java 7 (version `1.7.0_13` to be precise) in the path `C:\Program Files\Wolfram Research\Mathematica\10.1\SystemFiles\Java\Windows-x86-64\bin`.   I am not seeing any way I can change the way Mathematica associates the Java version.

Once I execute 
```
<<NetLogo `
```
evaluating `NLJavaDiagnostics[]` always returns `<|"javaVersion" -> "1.7.0_13", "javaArchitecture" -> "64"|>`

If I try:
```
NLStart["C:\\Program Files\\NetLogo 6.2.1", 
 CommandLine -> "C:\\Program Files\\Java\\jdk1.8.0_311\\bin\\
  java.exe"]
```

Mathematica ignores the specific path to java.exe and opens a window prompting `Choose a MathLink program to launch`. I can navigate to the specific java.exe file that appears in the CommandLine option. When I do, Mathematica pauses for about 15 seconds and then returns the following:

```
LinkObject::linkn: Argument LinkObject["C:\Program Files\Java\jdk1.8.0_311\bin\java.exe",361,5] in LinkReadyQ[LinkObject["C:\Program Files\Java\jdk1.8.0_311\bin\java.exe",361,5]] has an invalid LinkObject number; the link may be closed. >>

LinkObject::linkn: Argument LinkObject["C:\Program Files\Java\jdk1.8.0_311\bin\java.exe",361,5] in LinkConnectedQ[LinkObject["C:\Program Files\Java\jdk1.8.0_311\bin\java.exe",361,5]] has an invalid LinkObject number; the link may be closed. >>

LinkObject::linkn: Argument LinkObject["C:\Program Files\Java\jdk1.8.0_311\bin\java.exe",361,5] in LinkReadyQ[LinkObject["C:\Program Files\Java\jdk1.8.0_311\bin\java.exe",361,5]] has an invalid LinkObject number; the link may be closed. >>

General::stop: Further output of LinkObject::linkn will be suppressed during this calculation. >>

InstallJava::fail: A link to the Java runtime could not be established. >>

LoadJavaClass::fail: Java failed to load class NLink. >>

```
The curious thing is that when I provide what should be a valid CommandLine option, NLStart completely ignores and prompts me to `Choose a MathLink program to launch`.

I wish Wolfram Research would permit CCL to temporarily install a Mathematica 10 to troubleshoot this.

**Comment by LaCuneta** [comment]
I can at least answer one small mystery - when you run `NLJavaDiagnostics[]` it re-runs Java using the defaults, so it would still return Java 7 no matter what was used previously with `NLStart[]`.  You can run it with `NLJavaDiagnostics[CommandLine -> "/path/to/java"]`  to see if it'll start with an alternate Java version, or maybe give a different error.

Other than that I'm running low on ideas.  I did find [this post (section 3.2 in particular)](http://members.wolfram.com/meng/pages/computing/installing_and_configuring/installing_and_configuring_Java_on_macOS/#.YZ53ycXMJmN) that runs into a similar error.  The author there believed the issue to be with the `JAVA_HOME` environment variable being set to something not matching the Java version used.  So that might be something to check.  They use `Import["!echo $JAVA_HOME", "Text"]` and `Environment["JAVA_HOME"]` to report the values.  I'm just not clear on if they would need to match whatever the "new" Java version is or not?  I guess checking them and trying each options wouldn't be too bad - [here are some instructions for setting environment variables](https://www.opentechguides.com/how-to/article/windows-10/113/windows-10-set-path.html), just in case you need them.

I'm guessing updating to Mathematica 12 isn't an option for you?

**Comment by evolvingtech** [comment]
At the moment, updating to Mathematica 12 would be at considerable financial expense.

Good to know about supplying the CommandLine option with `NLJavaDiagnostics`. The challenge still remains that whenever I supply the CommandLine option such as:

`NLJavaDiagnostics[CommandLine -> "C:\\Program Files\\Java\\jdk-17.0.1\\bin\\java.exe"]`

totally ignores the `"/path/to/java" `and instead a window pops up to prompt me to navigate to the specific file. When the appropriate `java.exe` file is selected and the `Open` button is pressed, It reports that there are `invalid LinkObject` numbers. I suspect that CommandLine is not working as intended within. It might be worth revisiting how it is called within the recently updated `NetLogo.m` file.

Thanks for pointing out the post. The code in section 3.2 does not work exactly as shown in the post (which was written for MacOS with Mathematica 9). The output needs to be redirected by supplying `2>&1` in the string.

```
Import["!echo %JAVA_HOME% 2>&1", "Text"]

"C:\\Program Files\\Java\\jdk-17.0.1 "

Environment["JAVA_HOME"]

"C:\\Program Files\\Java\\jdk-17.0.1"

Import["!java -version 2>&1", "Text"]

"java version \"17.0.1\" 2021-10-19 LTS
Java(TM) SE Runtime Environment (build 17.0.1+12-LTS-39)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.1+12-LTS-39, mixed \
mode, sharing)"

```

**Comment by evolvingtech** [comment]
I did manage to get a hold of Mathematica 12 (though running on MacOS). I got that working though another item has come up that I will post as a separate issue. 

My suggestion is that if we cannot resolve getting Mathematica Link to work with Version 10 of Mathematica, that the NetLogo 6.2.X documentation be updated to indicate that Mathematica Link requires using a version of Mathematica subsequent to Version 10.
